name = pale_watcher
title = The Pale Watcher
description = Psychological horror mob featuring true quantum stalking, scaling cursed pages ritual, responsive horror vignette, flash camera stun, and ritual pyre banishment.
author = SaKeL
depends = x_mob_core
optional_depends = player_monoids, playerphysics, pova, default, mcl_core, everness, ethereal
min_minetest_version = 5.17.0
release = 1000
